name: url-shortener
include:
  - infrastructure.yaml
services:
  backend-app:
    build:
      dockerfile: ../Dockerfile
      args:
        JAR_FILE: target/url-shortener-backend-0.0.1-SNAPSHOT.jar
      tags:
        - localhost:8080/doroninav/url-shortener-backend:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: compose
    ports:
      - '8080:8080'
    depends_on:
      - mongodb-sharded
      - redis-cluster-master