spring:
  application:
    name: url-shortener-backend
  data:
    mongodb:
      uri: mongodb://shortener:short_pass@localhost:27017/shortener_db
      auto-index-creation: true
    redis:
      password: redis_pass
      cluster:
        nodes:
          - 'localhost:6379'
          - 'localhost:6380'
          - 'localhost:6381'
          - 'localhost:6382'
          - 'localhost:6383'
          - 'localhost:6384'
        max-redirects: 3
      lettuce:
        pool:
          enabled: true
          max-active: 50
          max-idle: 10
shortener:
  nodeId: 255
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'